agent_worker:
  path: '/agent_worker'
  defaults:
    _controller: 'AgentBundle:AgentWorker:index'
workflow_callback:
  path: '/workflow_callback/{workflow}'
  defaults:
    _controller: 'AgentBundle:WorkflowCallback:index'
  methods:
    - POST
