# 一个完整的permission配置如下：
# admin_user_manage:
#   name: 用户管理
#   children:               //可选
#   mode:                   //可选 none, modal, capsules（只有在tabs可用）
#   group:                  //可选 内置: topBtn, capsule, 也可以自定义
#   router_name: admin_user //可选
#   router_params:          //可选
#   blank:                  //可选
#   visible:                //可选
#   icon:                   //可选
#   data:                   //可选
#   before:                 //可选 菜单出现位置在同级的某个菜单之前
#   after:                  //可选 菜单出现位置在同级的某个菜单之后
#   disable:                //角色管理分配权限默认开启不用选中

web:
    name: web.basic_menu
    parent: null
    disable: true
    children:
        course_manage:
            name: web.course
            children:
                course_manage_info:
                    name: web.course.info_nav
                    router_params:
                        id: (course.id)
                    children:
                        course_manage_base:
                            name: web.course.info.base_side_nav
                            data:
                                side_nav: base
                            router_params:
                                id: (course.id)
                        course_manage_detail:
                            name: web.course.info.detail_side_nav
                            data:
                                side_nav: detail
                            router_params:
                                id: (course.id)
                        course_manage_picture:
                            name: web.course.info.picture_side_nav
                            data:
                                side_nav: picture
                            router_params:
                                id: (course.id)
                        course_manage_lesson:
                            name: web.course.info.lesson_side_nav
                            data:
                                side_nav: lesson
                            router_params:
                                id: (course.id)
                        live_course_manage_replay:
                            name: web.course.info.live_replay_side_nav
                            data:
                                side_nav: replay
                            router_params:
                                id: (course.id)
                        course_manage_files:
                            name: web.course.info.files_side_nav
                            data:
                                side_nav: files
                            router_params:
                                id: (course.id)
                course_manage_setting:
                    name: web.course.setting_nav
                    children:
                        course_manage_price:
                            name: web.course.setting.price_side_nav
                            data:
                                side_nav: price
                            router_params:
                                id: (course.id)
                        course_manage_teachers:
                            name: web.course.setting.teachers_side_nav
                            data:
                                side_nav: teachers
                            router_params:
                                id: (course.id)
                        course_manage_students:
                            name: web.course.setting.students_side_nav
                            data:
                                side_nav: students
                            router_params:
                                id: (course.id)
                            children:
                                course_manage_student_create:
                                    name: web.course.setting.students.create_btn
                course_manage_questions:
                    name: web.course.questions_nav
                    children:
                        course_manage_question:
                            name: web.course.questions.question_side_nav
                            data:
                                side_nav: question
                            router_params:
                                courseId: (course.id)
                        course_manage_testpaper:
                            name: web.course.questions.testpaper_side_nav
                            data:
                                side_nav: testpaper
                            router_params:
                                courseId: (course.id)
                course_manange_operate:
                    name: web.course.operate_nav
                    children:
                        course_manage_data:
                            name: web.course.operate.data_side_nav
                            data:
                                side_nav: course_manage_data
                            router_params:
                                id: (course.id)
                        course_manage_order:
                            name: web.course.operate.order_side_nav
                            data:
                                side_nav: course_manage_order
                            router_params:
                                id: (course.id)
        classroom_manage:
            name: web.classroom
            children:
                classroom_manage_settings:
                    name: web.classroom.setting_nav
                    children:
                        classroom_manage_set_info:
                            name: web.classroom.setting.base_side_nav
                            data:
                                side_nav: base
                            router_params:
                                id: (classroom.id)
                        classroom_manage_headteacher:
                            name: web.classroom.setting.headteacher_side_nav
                            data:
                                side_nav: headTeacher
                            router_params:
                                id: (classroom.id)
                        classroom_manage_teachers:
                            name: web.classroom.setting.teachers_side_nav
                            data:
                                side_nav: teachers
                            router_params:
                                id: (classroom.id)
                        classroom_manage_assistants:
                            name: web.classroom.setting.assistants_side_nav
                            data:
                                side_nav: assistants
                            router_params:
                                id: (classroom.id)
                classroom_manage_content:
                    name: web.classroom.content_nav
                    children:
                        classroom_manage_courses:
                            name: web.classroom.content.courses_side_nav
                            visible: (canManage)
                            data:
                                side_nav: courses
                            router_params:
                                id: (classroom.id)
                        classroom_manage_students:
                            name: web.classroom.content.students_side_nav
                            visible: (canManage)
                            data:
                                side_nav: students
                            router_params:
                                id: (classroom.id)
                        classroom_manage_testpaper:
                            name: web.classroom.content.testpaper_check_side_nav
                            visible: (canHandle)
                            data:
                                side_nav: testpaper-check
                            router_params:
                                id: (classroom.id)
                                status: reviewing
