# 将此文件重命名为 `.gitlag-ci.yml`，即可启用 Gilab CI。

variables:
  MYSQL_DATABASE: my_api_db_testing
  MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

before_script:
  - composer config -g repo.packagist composer https://packagist.phpcomposer.com


cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules
    - ~/.composer/vendor

deploy for develop:
  stage: deploy
  tags:
    - docker-ci-php-7.1
  script:
    - npm install yarn
    - node_modules/yarn/bin/yarn config set registry https://registry.npm.taobao.org
    - node_modules/yarn/bin/yarn
    - composer global require deployer/deployer -vvv
    - mkdir -p ~/.ssh
    - touch ~/.ssh/deployerkey
    - echo "$DEV_SERVER_PRIVATE_KEY" >> ~/.ssh/deployerkey
    - chmod 400  ~/.ssh/deployerkey
    - dep deploy dev
  only:
    - develop