cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - node_modules
    - ~/.composer/vendor

deploy for develop:
  stage: deploy
  image: codeages/ci-php71:6
  script:
    - npm install yarn
    - node_modules/yarn/bin/yarn config set registry https://registry.npm.taobao.org
    - node_modules/yarn/bin/yarn
    - mkdir -p ~/.ssh
    - touch ~/.ssh/deployerkey
    - echo "$DEV_SERVER_PRIVATE_KEY" >> ~/.ssh/deployerkey
    - chmod 400  ~/.ssh/deployerkey
    - dep deploy dev
  only:
    - develop